name: instagram_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animate_do: ^3.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: 6.1.0
  mock_data: ^2.0.1
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - 'assets/defaultProfilePicture.jpg'
